### ISSUE TITLE
cannot compile 

### ISSUE THREAD

**Issue by Pablete1234** [iEli2tyree011/EllyCheat#1]
maybe it's bcos i do not know how to compile with gradle, but gradle 2.4 does not work for me, i am running the "gradle build" command in the directory containing ellycheat-main directly downloaded from this repo

http://gyazo.com/ee59ab1ff5c7ce738e3c9f21495afb86

**Comment by Alfalik** [comment]
What's the message on the command prompt when you enter ```gradle --version```, also make sure you copied it using git bash, not the zip download on github.

**Comment by Pablete1234** [comment]
how do you compile it with git bash, is bash for windows a thing?

**Comment by Pablete1234** [comment]
gradle -v
http://gyazo.com/02dac9d55dec155f64edef191ee90f72

**Comment by Alfalik** [comment]
Download git bash (<a href="https://msysgit.github.io/">https://msysgit.github.io/</a>), then enter 3 simply commands:

```git clone https://github.com/iEli2tyree011/EllyCheat```
```cd EllyCheat```
```gradle build```

Here's an example of how it should be (in order). Tell me how it works

**Comment by Pablete1234** [comment]
thx in advance, i'm downloaing/intralling git atm

**Comment by Pablete1234** [comment]
http://gyazo.com/d02137a3c3645909185c539a75b979e9

**Comment by Alfalik** [comment]
Try to re-install gradle, personally found <a href="https://www.youtube.com/watch?v=joc8A2mKb7g">this</a> tutorial a good one. Make sure that you copied the gradle folder correctly to the Path and added the %GRADLE_HOME% at system variables. Get me back when you re-install it (or just check if you did all the steps)

**Comment by Pablete1234** [comment]
that one is exactly the one i used to install it, like a few hours ago

**Comment by Pablete1234** [comment]
i feel what i'm missing is java development kit that may be necessary for gradle to work

**Comment by Alfalik** [comment]
Try to install <a href="http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html">this</a>. Also, you need to add the route to your system variables to make it work. Find a tutorial if you don't know how

**Comment by Pablete1234** [comment]
still nothing, i think i didnt set java path correclty, i am not sure what the enviroment variable should be
i set:
JAVA_HOME as : E:\Programas\Java\jdk1.80_45
JRE_HOME as : E:\Programas\Java\jre1.80_45
and in path i set:
%JAVA_HOME%\lib

**Comment by Pablete1234** [comment]
ok. fine. i had to close and open git bash for it to take effect.

**Comment by Alfalik** [comment]
Does it compile? Did you get it built?

**Comment by Pablete1234** [comment]
yes i got it compiled
