### ISSUE TITLE
Readme is wrong, EllyCheat is intended for 1.8.6+

### ISSUE THREAD

**Issue by Pablete1234** [iEli2tyree011/EllyCheat#2]
Tps error:
http://gyazo.com/41c7dd5d1f35da80c9b2d1072fb3c08c
CPS error:
http://gyazo.com/7c2482081f6471aaeb6011afc9714587

I do have op, so i should have the permission
server version: 
http://gyazo.com/b6dbe73488b835ebf7fcb6c47bfb5b92

**Comment by Alfalik** [comment]
Do ```/version``` in-game and send me an screenshot

**Comment by Pablete1234** [comment]
look at the 3rd image

**Comment by Alfalik** [comment]
EllyCheat is for 1.8.6 or superior, the readme is wrong.

**Comment by Pablete1234** [comment]
oh :c well, then the readme should be updated,

**Comment by Alfalik** [comment]
@Pablete1234 Make a Pull Request :P

**Comment by Pablete1234** [comment]
@Alfalik done

**Comment by Pablete1234** [comment]
works great in 1.8 
http://gyazo.com/04e937afb354e1fe48d0d59dceeaebce
