### ISSUE TITLE
My server can´t load "EllyCheat.jar"

### ISSUE THREAD

**Issue by Prodigy4532** [iEli2tyree011/EllyCheat#4]
Hi, i have a problem with my server, i can´t use "EllyCheat", This is the log
http://pastebin.com/Ch2KE727

I have one server in "localhost" and here i can use EllyCheat, and i have the same .jar
http://pastebin.com/3NcwK9vX

I honestly do not know what 's going on.

**Comment by Alfalik** [comment]
Try running the server  only using EllyCheat. Another plugin may cause problems. Get me back with the results.

**Comment by Prodigy4532** [comment]
i put my plugin in my localhost and i can use "EllyCheat", i remove all plugin in my beastnode server and i cant, http://pastebin.com/C8naYq4F

**Comment by TiTo-418** [comment]
Me neither http://pastebin.com/qFC1GuwE

**Comment by TiTo-418** [comment]
@iEli2tyree011 Look at this https://github.com/Superior-Development/CommandViewer/issues/9

**Comment by iEli2tyree011** [comment]
@TiTo-418 I'm not maintaining this project anymore, but I'll help out with fixing it up. You're all using an outdated version of Java, use Java 8.

**Comment by TiTo-418** [comment]
The shared hosts uses Java 7

**Comment by iEli2tyree011** [comment]
@TiTo-418 For now, then, someone would have to build the plugin using Java 7.

**Comment by unixfox** [comment]
Unable to build with Java 7 (openjdk-7-jdk) :

>Download https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-chat/1.8-SNAPSHOT/bungeecord-chat-1.8-20150716.221126-85.pom
Download https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-parent/1.8-SNAPSHOT/bungeecord-parent-1.8-20150716.221116-85.pom
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.pom
Download https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.8.6-R0.1-SNAPSHOT/spigot-api-1.8.6-R0.1-20150605.095628
-29.jar
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar
Download https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-chat/1.8-SNAPSHOT/bungeecord-chat-1.8-20150716.221126-85.jar
Download https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
:compileJava FAILED
 
>FAILURE: Build failed with an exception.
 
>* What went wrong:
>Execution failed for task ':compileJava'.
> invalid source release: 1.8
 
>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
>BUILD FAILED
 
>Total time: 17.494 secs

**Comment by iEli2tyree011** [comment]
@unixfox The plugin is designed for Java 8, and will only compile using Java 8.

**Comment by Prodigy4532** [comment]
I am recreating this plugin with Java 7 but, i have 2 ploblems.

ee.ellytr.autoclick.cps.CPSRunnable.java

Line 31: ` Bukkit.getOnlinePlayers().stream().filter(toSend -> toSend.hasPermission("ellycheat.cps.warning")).forEach(toSend -> {`
Line 50: ` Bukkit.getOnlinePlayers().stream().filter(toSend -> toSend.hasPermission("ellycheat.cps.warning")).forEach(toSend -> {`

**Comment by unixfox** [comment]
@Prodigy4532 why close this issue ? does the problem is fixed ?

**Comment by Prodigy4532** [comment]
Yes, i make this plugin with java 7, and my host "Minecrafted.net" Have Java8.

**Comment by unixfox** [comment]
@Prodigy4532 can you provide me your ellycheat in java 7 ?

**Comment by Prodigy4532** [comment]
sure, addme in skype: camilo0mi
